import { CreateTagDto } from "src/modules/mariadb/tags/dto/create-tag.dto";

export const sampleTags: CreateTagDto[] = [
  { name: 'Dynamic Programming' },
  { name: 'Graph' },
  { name: 'Greedy' },
  { name: 'Sorting' },
  { name: 'Searching' },
  { name: 'Binary Search' },
  { name: 'Recursion' },
  { name: 'Bit Manipulation' },
  { name: 'Backtracking' },
  { name: 'Mathematics' },
  { name: 'Number Theory' },
  { name: 'Combinatorics' },
  { name: 'Probability' },
  { name: 'Graph Theory' },
  { name: 'String Processing' },
  { name: 'Trie' },
  { name: 'Segment Tree' },
  { name: 'Fenwick Tree' },
  { name: 'Divide and Conquer' },
  { name: 'Game Theory' },
  { name: 'Sliding Window' },
  { name: 'Two Pointers' },
  { name: 'Heap' },
  { name: 'Priority Queue' },
  { name: 'Union Find' },
  { name: 'Topological Sort' },
  { name: 'Shortest Path' },
  { name: 'Minimum Spanning Tree' },
  { name: 'Breadth-First Search' },
  { name: 'Depth-First Search' },
  { name: 'Memoization' },
  { name: 'Linked List' },
  { name: 'Stack' },
  { name: 'Queue' },
  { name: 'Hash Table' },
  { name: 'Binary Tree' },
  { name: 'Binary Indexed Tree' },
  { name: 'Suffix Array' },
  { name: 'Geometry' },
  { name: 'Simulation' }
];
